### ISSUE TITLE
Already works for Sway

### ISSUE THREAD

**Issue by mhoekveen** [jamesofarrell/i3-swallow#10]
[Sway](https://github.com/swaywm/sway) is an i3-compatible window manager, and [i3ipc-python](https://github.com/altdesktop/i3ipc-python) also supports it out of the box. As such, this project works in sway as well.

To avoid confusion, it might be a good thing to advertise this support in the readme/doc. I was about to try and add support myself when I realized support was already there.

**Comment by travankor** [comment]
It doesn't seem to work for floating windows under sway.

**Comment by Uniminin** [comment]
well it should

**Comment by loannaflip** [comment]
= Already works for Sway
Well, quite obvious.
