### ISSUE TITLE
Package on pypi

### ISSUE THREAD

**Issue by ViliamV** [jamesofarrell/i3-swallow#25]
Hi! First of all I appreciate your work - thanks!

I just wanted to inform you that I forked this repo just to package it with Poetry and publish it on pypi for easier installation.

[package](https://pypi.org/project/i3-swallow/)

[repo](https://github.com/ViliamV/i3-swallow)

If you want to maintain it yourself I can make PR with changes and submit it here. :slightly_smiling_face:

**Comment by IvarWithoutBones** [comment]
Thanks for the work! This makes packaging this tool for `nix` much easier :)

**Comment by IvarWithoutBones** [comment]
@jamesofarrell would love to get this merged, if you're interested :blush:

**Comment by jamesofarrell** [comment]
There you go, merged

**Comment by IvarWithoutBones** [comment]
Thank you, i appreciate it :blush:
